from __future__ import annotations

import numpy as np

data_model = "icoads"
release = "r302"
deck = "d992"
input_dir = f"{data_model}/{release}/{deck}"
cdm = f"icoads_{release}_{deck}_2022-01-01_subset"
suffix = "imma"
level0 = f"{input_dir}/input/{cdm}.{suffix}"
release = "release_8.0"

process_list = "114-992"
year_init = "2020"
year_end = "2025"

table_names = [
    "header",
    "observations-at",
    "observations-dpt",
    "observations-slp",
    "observations-sst",
    "observations-wbt",
    "observations-wd",
    "observations-ws",
]

table_names_next = [
    "header",
    "observations-at",
    "observations-dpt",
    "observations-slp",
    "observations-sst",
    "observations-wd",
    "observations-ws",
]

prev_level = {
    "level1a": "level0",
    "level1b": "level1a",
    "level1c": "level1b",
    "level1d": "level1c",
    "level1e": "level1d",
    "level2": "level1e",
    "level3": "level2",
}

level_input = {
    "level1a": "datasets",
    "level1b": release,
    "level1c": release,
    "level1d": release,
    "level1e": release,
    "level2": release,
    "level3": release,
}

which_tables = {
    "level1a": table_names,
    "level1b": table_names_next,
    "level1c": table_names_next,
    "level1d": table_names_next,
    "level1e": table_names_next,
    "level2": table_names_next,
    "level3": table_names_next,
}

pattern = {
    "level1a": "icoads_r???_d???_????-??-??_subset.imma",
    "level1b": "header-icoads_r???_d???_????-??-??_subset.psv",
    "level1c": "header-icoads_r???_d???_????-??-??_subset.psv",
    "level1d": "header-icoads_r???_d???_????-??-??_subset.psv",
    "level1e": "header-icoads_r???_d???_????-??-??_subset.psv",
    "level2": "header-icoads_r???_d???_????-??-??_subset.psv",
    "level3": "header-icoads_r???_d???_????-??-??_subset.psv",
}
pattern_out = {"level3": f"pressure-data-2022-01-{release}-000000.psv"}

manipulation = {
    "level1b": {
        ("header", "duplicate_status"): [
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "1",
            "1",
            "3",
            "3",
            "3",
        ],
        ("header", "report_quality"): [
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "1",
            "1",
            "1",
        ],
        ("header", "duplicates"): [
            "null",
            "null",
            "null",
            "null",
            "null",
            "null",
            "null",
            "null",
            "{ICOADS-302-LQWUT8}",
            "{ICOADS-302-LQWUT6,ICOADS-302-LQWUT7}",
            "{ICOADS-302-LQWUT5}",
            "{ICOADS-302-LQWUT5}",
            "{ICOADS-302-LQWUT4}",
        ],
    },
    "level1d": {
        ("header", "station_name"): [
            "null",
            "FF HELMER HANSEN",
            "WAVERIDER TFSTD",
            "null",
            "WAVERIDER TFDRN",
            "VESLEFRIKK A",
            "OSEBERG C",
            "SLEIPNER B",
            "null",
            "HULDRAFELTET",
            "HULDRAFELTET",
            "HULDRAFELTET",
            "null",
        ],
        # ("header", "platform_sub_type"): [
        #    "null",
        #    "RV",
        #    "OT",
        #    "null",
        #    "OT",
        #    "null",
        #    "null",
        #    "null",
        #    "null",
        #    "null",
        #    "null",
        #    "null",
        #    "null",
        # ],
        ("header", "station_record_number"): [
            "1",
            "1",
            "0",
            "1",
            "0",
            "3",
            "3",
            "3",
            "1",
            "3",
            "3",
            "3",
            "1",
        ],
        ("header", "report_duration"): [
            "11",
            "11",
            "11",
            "11",
            "11",
            "11",
            "11",
            "11",
            "11",
            "11",
            "11",
            "11",
            "11",
        ],
        ("observations-at", "sensor_id"): [
            "null",
            "null",
            np.nan,
            "null",
            np.nan,
            "null",
            "null",
            "null",
            "null",
            "null",
            "null",
            "null",
            "null",
        ],
        ("observations-dpt", "sensor_id"): [
            np.nan,
            "null",
            np.nan,
            "null",
            np.nan,
            "null",
            "null",
            "null",
            "null",
            "null",
            "null",
            "null",
            "null",
        ],
        ("observations-slp", "sensor_id"): [
            "null",
            "null",
            np.nan,
            "null",
            np.nan,
            "null",
            "null",
            "null",
            "null",
            "null",
            "null",
            "null",
            "null",
        ],
        ("observations-sst", "sensor_id"): [
            "null",
            "null",
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
        ],
        ("observations-wd", "sensor_id"): [
            "null",
            "null",
            np.nan,
            "null",
            np.nan,
            "null",
            "null",
            "null",
            "null",
            "null",
            "null",
            "null",
            "null",
        ],
        ("observations-ws", "sensor_id"): [
            "null",
            "null",
            np.nan,
            "null",
            np.nan,
            "null",
            "null",
            "null",
            "null",
            "null",
            "null",
            "null",
            "null",
        ],
        ("observations-at", "sensor_automation_status"): [
            "5",
            "5",
            np.nan,
            "5",
            np.nan,
            "5",
            "5",
            "5",
            "5",
            "5",
            "5",
            "5",
            "5",
        ],
        ("observations-dpt", "sensor_automation_status"): [
            np.nan,
            "5",
            np.nan,
            "5",
            np.nan,
            "5",
            "5",
            "5",
            "5",
            "5",
            "5",
            "5",
            "5",
        ],
        ("observations-slp", "sensor_automation_status"): [
            "5",
            "5",
            np.nan,
            "5",
            np.nan,
            "5",
            "5",
            "5",
            "5",
            "5",
            "5",
            "5",
            "5",
        ],
        ("observations-sst", "sensor_automation_status"): [
            "5",
            "5",
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
        ],
        ("observations-wd", "sensor_automation_status"): [
            "5",
            "5",
            np.nan,
            "5",
            np.nan,
            "5",
            "5",
            "5",
            "5",
            "5",
            "5",
            "5",
            "5",
        ],
        ("observations-ws", "sensor_automation_status"): [
            "5",
            "5",
            np.nan,
            "5",
            np.nan,
            "5",
            "5",
            "5",
            "5",
            "5",
            "5",
            "5",
            "5",
        ],
    },
    "level1e": {
        ("header", "longitude"): [
            "31.6",
            "18.9",
            "null",
            "8.1",
            "null",
            "9.1",
            "10.1",
            "11.1",
            "12.1",
            "13.1",
            "13.1",
            "13.1",
            "12.1",
        ],
        ("header", "latitude"): [
            "75.6",
            "69.6",
            "null",
            "66.0",
            "null",
            "67.0",
            "68.0",
            "69.0",
            "70.0",
            "71.0",
            "71.0",
            "71.0",
            "70.0",
        ],
        ("header", "station_course"): [
            "135.0",
            "null",
            "null",
            "0.0",
            "null",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
            "0.0",
        ],
        ("header", "report_timestamp"): [
            "null",
            "2022-01-01",
            "null",
            "2022-01-01",
            "null",
            "2022-01-02",
            "2022-01-03",
            "2022-01-04",
            "2022-01-05",
            "2022-01-06",
            "2022-01-06",
            "2022-01-06",
            "2022-01-05",
        ],
        ("header", "report_quality"): [
            "1",
            "0",
            "null",
            "0",
            "null",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
        ],
        ("header", "report_time_quality"): [
            "4",
            "2",
            "null",
            "2",
            "null",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ],
        ("observations-at", "longitude"): [
            "31.6",
            "18.9",
            "null",
            "8.1",
            "null",
            "9.1",
            "10.1",
            "11.1",
            "12.1",
            "13.1",
            "13.1",
            "13.1",
            "12.1",
        ],
        ("observations-at", "latitude"): [
            "75.6",
            "69.6",
            "null",
            "66.0",
            "null",
            "67.0",
            "68.0",
            "69.0",
            "70.0",
            "71.0",
            "71.0",
            "71.0",
            "70.0",
        ],
        ("observations-at", "date_time"): [
            "null",
            "2022-01-01",
            "null",
            "2022-01-01",
            "null",
            "2022-01-02",
            "2022-01-03",
            "2022-01-04",
            "2022-01-05",
            "2022-01-06",
            "2022-01-06",
            "2022-01-06",
            "2022-01-05",
        ],
        ("observations-at", "quality_flag"): [
            "2",
            "0",
            "null",
            "0",
            "null",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
        ],
        ("observations-dpt", "longitude"): [
            np.nan,
            "18.9",
            "null",
            "8.1",
            "null",
            "9.1",
            "10.1",
            "11.1",
            "12.1",
            "13.1",
            "13.1",
            "13.1",
            "12.1",
        ],
        ("observations-dpt", "latitude"): [
            np.nan,
            "69.6",
            "null",
            "66.0",
            "null",
            "67.0",
            "68.0",
            "69.0",
            "70.0",
            "71.0",
            "71.0",
            "71.0",
            "70.0",
        ],
        ("observations-dpt", "date_time"): [
            np.nan,
            "2022-01-01",
            "null",
            "2022-01-01",
            "null",
            "2022-01-02",
            "2022-01-03",
            "2022-01-04",
            "2022-01-05",
            "2022-01-06",
            "2022-01-06",
            "2022-01-06",
            "2022-01-05",
        ],
        ("observations-dpt", "quality_flag"): [
            np.nan,
            "0",
            "null",
            "0",
            "null",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
        ],
        ("observations-slp", "longitude"): [
            "31.6",
            "18.9",
            "null",
            "8.1",
            "null",
            "9.1",
            "10.1",
            "11.1",
            "12.1",
            "13.1",
            "13.1",
            "13.1",
            "12.1",
        ],
        ("observations-slp", "latitude"): [
            "75.6",
            "69.6",
            "null",
            "66.0",
            "null",
            "67.0",
            "68.0",
            "69.0",
            "70.0",
            "71.0",
            "71.0",
            "71.0",
            "70.0",
        ],
        ("observations-slp", "date_time"): [
            "null",
            "2022-01-01",
            "null",
            "2022-01-01",
            "null",
            "2022-01-02",
            "2022-01-03",
            "2022-01-04",
            "2022-01-05",
            "2022-01-06",
            "2022-01-06",
            "2022-01-06",
            "2022-01-05",
        ],
        ("observations-slp", "observation_value"): [
            "101140.0",
            "101100.0",
            "null",
            "100360.0",
            "null",
            "100360.0",
            "100360.0",
            "100360.0",
            "100360.0",
            "100360.0",
            "100360.0",
            "100360.0",
            "100360.0",
        ],
        ("observations-slp", "quality_flag"): [
            "2",
            "2",
            "null",
            "2",
            "null",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
        ],
        ("observations-sst", "longitude"): [
            "31.6",
            "18.9",
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
        ],
        ("observations-sst", "latitude"): [
            "75.6",
            "69.6",
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
        ],
        ("observations-sst", "date_time"): [
            "null",
            "2022-01-01",
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
        ],
        ("observations-sst", "quality_flag"): [
            "2",
            "0",
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
            np.nan,
        ],
        ("observations-wd", "longitude"): [
            "31.6",
            "18.9",
            "null",
            "8.1",
            "null",
            "9.1",
            "10.1",
            "11.1",
            "12.1",
            "13.1",
            "13.1",
            "13.1",
            "12.1",
        ],
        ("observations-wd", "latitude"): [
            "75.6",
            "69.6",
            "null",
            "66.0",
            "null",
            "67.0",
            "68.0",
            "69.0",
            "70.0",
            "71.0",
            "71.0",
            "71.0",
            "70.0",
        ],
        ("observations-wd", "date_time"): [
            "null",
            "2022-01-01",
            "null",
            "2022-01-01",
            "null",
            "2022-01-02",
            "2022-01-03",
            "2022-01-04",
            "2022-01-05",
            "2022-01-06",
            "2022-01-06",
            "2022-01-06",
            "2022-01-05",
        ],
        ("observations-wd", "observation_value"): [
            "220.0",
            "240.0",
            "null",
            "160.0",
            "null",
            "160.0",
            "-50.0",
            "460.0",
            "160.0",
            "0.0",
            "0.0",
            "0.0",
            "160.0",
        ],
        ("observations-wd", "quality_flag"): [
            "2",
            "0",
            "null",
            "0",
            "null",
            "0",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
        ],
        ("observations-ws", "longitude"): [
            "31.6",
            "18.9",
            "null",
            "8.1",
            "null",
            "9.1",
            "10.1",
            "11.1",
            "12.1",
            "13.1",
            "13.1",
            "13.1",
            "12.1",
        ],
        ("observations-ws", "latitude"): [
            "75.6",
            "69.6",
            "null",
            "66.0",
            "null",
            "67.0",
            "68.0",
            "69.0",
            "70.0",
            "71.0",
            "71.0",
            "71.0",
            "70.0",
        ],
        ("observations-ws", "date_time"): [
            "null",
            "2022-01-01",
            "null",
            "2022-01-01",
            "null",
            "2022-01-02",
            "2022-01-03",
            "2022-01-04",
            "2022-01-05",
            "2022-01-06",
            "2022-01-06",
            "2022-01-06",
            "2022-01-05",
        ],
        ("observations-ws", "quality_flag"): [
            "2",
            "0",
            "null",
            "0",
            "null",
            "1",
            "0",
            "0",
            "1",
            "1",
            "1",
            "1",
            "1",
        ],
    },
    "level3": [
        ("header", "station_name"),
        ("header", "primary_station_id"),
        ("header", "report_id"),
        ("observations-slp", "observation_id"),
        ("header", "longitude"),
        ("header", "latitude"),
        ("header", "height_of_station_above_sea_level"),
        ("header", "report_timestamp"),
        ("header", "report_meaning_of_timestamp"),
        ("header", "report_duration"),
        ("observations-slp", "observed_variable"),
        ("observations-slp", "units"),
        ("observations-slp", "observation_value"),
        ("observations-slp", "quality_flag"),
        ("header", "source_id"),
        ("observations-slp", "data_policy_licence"),
        ("header", "report_type"),
        ("observations-slp", "value_significance"),
    ],
}

drops = {
    "level1a": [0, 5, 6, 7, 9, 10, 11],
    "level1b": [2, 4],
    "level1c": [0, 3],
    "level1e": [2, 4],
    "level3": [2, 4],
}

reindex = ["level1b"]
