#
# cdm_reader_mapper documentation build configuration file
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

from __future__ import annotations

import sys
import warnings
from pathlib import Path

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# sys.path.insert(0, os.path.abspath('.'))

sys.path.insert(0, str((Path(__file__).parent.parent / "..").resolve()))
sys.path.insert(0, str((Path(__file__).parent.parent / ".").resolve()))

import glamod_marine_processing  # noqa

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.viewcode",
    "sphinx.ext.extlinks",
    "sphinx.ext.mathjax",
    "sphinx.ext.napoleon",
    "sphinx.ext.coverage",
    "sphinx.ext.todo",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.intersphinx",
    "myst_nb",
    "IPython.sphinxext.ipython_console_highlighting",
    "sphinx_autodoc_typehints",
    "sphinx_copybutton",
]

autosectionlabel_prefix_document = True
autosectionlabel_maxdepth = 2

autosummary_generate = True
autodoc_typehints = "description"
autodoc_typehints_format = "fully-qualified"
autodoc_typehints_description_target = "documented_params"
python_use_unqualified_type_names = True

# typehints_use_signature = True
# typehints_fully_qualified = False

napoleon_numpy_docstring = True
napoleon_use_rtype = False
napoleon_use_param = False
napoleon_use_ivar = True
napoleon_preprocess_types = True
napoleon_type_aliases = {
    "Iterable": ":term:`iterable`",
    "Hashable": ":term:`hashable`",
}

# To ensure that underlined fields (e.g. `_field`) are shown in the docs.
autodoc_default_options = {
    "members": True,
    "undoc-members": True,
    "private-members": False,
    "special-members": False,
}

extlinks = {
    "issue": ("https://github.com/glamod/glamod-marine-processing/issues/%s", "#%s"),
    "pull": ("https://github.com/glamod/glamod-marine-processing/pull/%s", "#%s"),
    "user": ("https://github.com/%s", "@%s"),
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix of source filenames.
source_suffix = {".rst": "restructuredtext"}

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = "index"

remove_from_toctrees = ["generated/*"]

# General information about the project.
project = "glamod_marine_processing"
copyright = "2019-2026, Ludwig Lierhammer, Axel Andersson, Tina Leiding, Richard Cornes, Elizabeth Kent, Joseph Siddons and John Kennedy"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = glamod_marine_processing.__version__
# The full version, including alpha/beta/rc tags.
release = glamod_marine_processing.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = "en"

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ["_build", "**.ipynb_checkpoints"]  # , "logo"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_title = "glamod-marine-processing Official Documentation"
html_short_title = "glamod_marine_processing"
html_theme = "furo"

# -- Options for HTMLHelp output ---------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "glamod_marine_processingdoc"

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).

# If true, show URL addresses after external links.
# man_show_urls = False

# disable warnings
warnings.filterwarnings("ignore")

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    "numpy": ("https://numpy.org/doc/stable", None),
    "pandas": ("https://pandas.pydata.org/pandas-docs/stable", None),
    "python": ("https://docs.python.org/3/", None),
    "xarray": ("https://docs.xarray.dev/en/stable", None),
}
