name: License Scanning

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    name: "license-scanning"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run FOSSA scan and upload build data
        uses: fossa-contrib/fossa-action@d28f0c947e7406706981a62a91ecc009bcc39fd7 # v4.0.0
        with:
          fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
